import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import { useEffect } from "react";
import axios from "axios";
import { parseCookies, setCookie, destroyCookie } from "nookies";

const CLIENT_ID =
  "80d546a81142ed877305322b8fb8df72a7aaf73a1e584e092064855b7e29d7d2";
const CLIENT_SECRET =
  "ea4d8987ea756e1ff64f43a7a43ca27475bb2098751db2c582d16c46da79b4e6";

export default function Home() {
  const router = useRouter();

  const authorize = (e) => {
    e.preventDefault();
    router.push(`https://dribbble.com/oauth/authorize?client_id=${CLIENT_ID}`);
  };
  useEffect(() => {
    const { code } = router.query;
    async function getAccessToken() {
      try {
        console.log(router.pathname);
        const response = await axios.post(
          `https://dribbble.com/oauth/token?client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&code=${code}`
        );
        console.log(response);
        const { access_token: accessToken } = response.data;
        setCookie(null, "accessToken", accessToken, {
          maxAge: 24 * 60 * 60,
          path: "/",
        });
        const cookies = parseCookies();
        console.log({ cookies });
        // console.log(accessTokecookie);
        const dribbbleShots = await axios.get(
          `https://api.dribbble.com/v2/user`,
          {
            headers: {
              Authorization: `Bearer ${accessToken}`,
            },
          }
        );
        console.log({ dribbbleShots });
      } catch (error) {
        console.warn(error);
      }
    }
    if (code) {
      console.log(code);
      getAccessToken();
    }
  }, [router]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={authorize}>Integrate Dribbble</button>

        {/* <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
